# Generated by Django 5.1.2 on 2024-10-29 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('dt_scheduled', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 5, 1, 37, 13, 35950, tzinfo=datetime.timezone.utc), null=True, verbose_name='Scheduled for')),
                ('dt_completed', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled for')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['title'],
            },
        ),
    ]
