# Generated by Django 5.1.2 on 2024-11-14 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_dt_canceled_alter_task_dt_scheduled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dt_scheduled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 21, 20, 41, 10, 644880, tzinfo=datetime.timezone.utc), null=True, verbose_name='Scheduled for'),
        ),
        migrations.AlterField(
            model_name='taskcontrol',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 20, 41, 10, 645380, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
