# Generated by Django 5.1.2 on 2024-11-14 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_dt_scheduled_alter_taskcontrol_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcontrol',
            name='type',
            field=models.CharField(choices=[('HS', 'Historic'), ('SC', 'Schedule')], default='HS', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dt_scheduled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 21, 21, 9, 53, 665174, tzinfo=datetime.timezone.utc), null=True, verbose_name='Scheduled for'),
        ),
        migrations.AlterField(
            model_name='taskcontrol',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 21, 9, 53, 665979, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
